using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Eryph.ConfigModel.Core.Validation.Tests;

public class StorageIdentifierTests
{
    [Fact]
    public void Validate_AutoGeneratedId_ReturnsSuccess()
    {
        var result = StorageIdentifier.NewValidation("BE8BUPERXP1C");

        result.Should().BeSuccess()
            .Which.Value.Should().Be("be8buperxp1c");
    }
}
