using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Eryph.ConfigModel.Core.Validation.Tests;

public class StorageIdentifierTests
{
    [Fact]
    public void Validate_AutoGeneratedId_ReturnsSuccess()
    {
        const string id = "BE8BUPERXP1C";

        var result = StorageIdentifier.Validate(id);

        result.Should().BeSuccess()
            .Which.Value.Should().Be(id);
    }
}
